
import layouts from "../assets/layouts.png";
import games from "../assets/games.png";
import todo from "../assets/todo.png";

export const projects = {
  en: [
    {
      id: 1,
      title: "Website Layout of Supabase",
      img: layouts,
      skills: "React JS / Tailwind",
      duration: "12 hours",
      category: "Layouts",
      link: "https://tailwind-1-j7qg.vercel.app/",
      githubLink: "https://github.com/tedbundy12/tailwind-1",
      demo: "Has",
      likes: 0,
    },
    {
      id: 2,
      title: "Website Layout of LaslesVPN",
      img: layouts,
      skills: "React JS / Tailwind",
      duration: "9 hours",
      category: "Layouts",
      link: "https://laselvpnn.vercel.app/",
      githubLink: "https://github.com/tedbundy12/thirdproject",
      demo: "Has",
      likes: 0,
    },
    {
      id: 3,
      title: "Simple ToDo Planner",
      img: todo,
      skills: "React JS / Tailwind",
      duration: "2 hours",
      category: "Others",
      link: "https://todoo-git-main-tedbundy12s-projects.vercel.app/",
      githubLink: "https://github.com/tedbundy12/todoo",
      demo: "Has",
      likes: 0,
    },
    {
      id: 4,
      title: "Agar.Io Clone ( not finished )",
      img: games,
      skills: "Node JS / Socket.io",
      duration: "5 hours",
      category: "Games",
      link: "/",
      githubLink: "https://github.com/tedbundy12/agar.io",
      demo: "None",
      likes: 0,
    },
    {
      id: 5,
      title: "Simple Drone Game",
      img: games,
      skills: "HTML / CSS / JavaScript",
      duration: "1 hours",
      category: "Games",
      link: "https://drone-game-nine.vercel.app/",
      githubLink: "https://github.com/tedbundy12/drone-game",
      demo: "Has",
      likes: 0,
    },
  ],
  ru: [
    {
      id: 1,
      title: "Вёрстка сайта Supabase",
      img: layouts,
      skills: "React JS / Tailwind",
      duration: "12 часов",
      category: "Вёрстка",
      link: "https://tailwind-1-j7qg.vercel.app/",
      githubLink: "https://github.com/tedbundy12/tailwind-1",
      demo: "Есть",
      likes: 0,
    },
    {
      id: 2,
      title: "Вёрстка сайта LaslesVPN",
      img: layouts,
      skills: "React JS / Tailwind",
      duration: "9 часов",
      category: "Вёрстка",
      link: "https://laselvpnn.vercel.app/",
      githubLink: "https://github.com/tedbundy12/thirdproject",
      demo: "Есть",
      likes: 0,
    },
    {
      id: 3,
      title: "Простой планировщик задач",
      img: todo,
      skills: "React JS / Tailwind",
      duration: "2 часа",
      category: "Другое",
      link: "https://todoo-git-main-tedbundy12s-projects.vercel.app/",
      githubLink: "https://github.com/tedbundy12/todoo",
      demo: "Есть",
      likes: 0,
    },
    {
      id: 4,
      title: "Клон игры Агарио ( не закончен )",
      img: games,
      skills: "Node JS / Socket.io",
      duration: "5 часов",
      category: "Игры",
      link: "https://todo-tailwind-livid.vercel.app/",
      githubLink: "https://github.com/tedbundy12/agar.io",
      demo: "Нет",
      likes: 0,
    },
    {
      id: 5,
      title: "Простая игра с дроном",
      img: games,
      skills: "HTML / CSS / JavaScript",
      duration: "1 Часов",
      category: "Игры",
      link: "https://drone-game-nine.vercel.app/",
      githubLink: "https://github.com/tedbundy12/drone-game",
      demo: "Есть",
      likes: 0,
    },
  ],
};
